// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjeblhorguaflmhjkpwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZWJsaG9yZ3VhZmxtaGprcHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MjcyMzcsImV4cCI6MjA3ODAwMzIzN30.jIvV5pGIA32yy0Vanm3sC0xfSvCbyhrvgwMmTaABOUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});